In [42]:
file_prefix = "Fusion__Campaigns_2022-01-17_0706.csv"

In [49]:
file_name = file_prefix.lower()

aux = file_name.split("__")
creation_dt = aux[1].split("_")[1]
time = aux[1].split("_")[2]
time = time.split(".")[0]
creation_datetime = f"{creation_dt} {time[:2]}:{time[2:]}:00"

destination_prefix = (
    f"skai/fusion_data_campaigns/p_creation_dt={creation_dt}/{file_name}"
)

print(destination_prefix)
print(creation_datetime)

skai/fusion_data_campaigns/p_creation_dt=2022-01-17/fusion__campaigns_2022-01-17_0706.csv
2022-01-17 07:06:00

In [ ]:
# skai/fusion_data_campaigns/p_creation_dt=2022-01-03/fusion_data_campaigns_20220103101323.jsonl

In [2]:
import pandas as pd

In [34]:
df = pd.read_csv("/Users/emif/Downloads/Fusion__Campaigns_2022-01-18_0420.csv")

In [35]:
df.head()

,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1m9BXbQfgJRMGTmGb,5737,2022-01-17,695.0,2.0,0,0.330824759445161,0.1,0.0,0.2
0,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,13oDhNbfK6HW0ne3r,5738,2022-01-17,53.0,1.0,0.0,0.376456,0.0,0.0,0.0
1,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1WR/NpFf1YbHQnNJi,5739,2022-01-17,1865.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1+yH3eK/qw2Jfg8HT,5740,2022-01-17,14.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1HHo8XQfgJRMqaxYJ,5741,2022-01-17,38.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1XyrGJbfK6HXSmWyO,5742,2022-01-17,76.0,1.0,0.0,0.022816,0.0,0.0,0.0

In [36]:
df.columns = [
    "currency",
    "profile_name",
    "profile_id",
    "profile_currency",
    "status",
    "channel",
    "campaign_name",
    "campaign_id",
    "dt",
    "impressions",
    "clicks",
    "conversions",
    "cost",
    "rev",
    "imp_share",
    "conv_rate",
]

In [37]:
df.head()

,currency,profile_name,profile_id,profile_currency,status,channel,campaign_name,campaign_id,dt,impressions,clicks,conversions,cost,rev,imp_share,conv_rate
0,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,13oDhNbfK6HW0ne3r,5738,2022-01-17,53.0,1.0,0.0,0.376456,0.0,0.0,0.0
1,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1WR/NpFf1YbHQnNJi,5739,2022-01-17,1865.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1+yH3eK/qw2Jfg8HT,5740,2022-01-17,14.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1HHo8XQfgJRMqaxYJ,5741,2022-01-17,38.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1XyrGJbfK6HXSmWyO,5742,2022-01-17,76.0,1.0,0.0,0.022816,0.0,0.0,0.0

In [40]:
creation_datetime = "2022-01-18"
df["creation_datetime"] = f"{creation_datetime} {datetime.now().strftime('%H:%M:%S')}"

In [41]:
df.head()

,currency,profile_name,profile_id,profile_currency,status,channel,campaign_name,campaign_id,dt,impressions,clicks,conversions,cost,rev,imp_share,conv_rate,creation_date,creation_datetime
0,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,13oDhNbfK6HW0ne3r,5738,2022-01-17,53.0,1.0,0.0,0.376456,0.0,0.0,0.0,2022-01-18 12:26:36,2022-01-18 12:26:43
1,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1WR/NpFf1YbHQnNJi,5739,2022-01-17,1865.0,0.0,0.0,0.000000,0.0,0.0,0.0,2022-01-18 12:26:36,2022-01-18 12:26:43
2,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1+yH3eK/qw2Jfg8HT,5740,2022-01-17,14.0,0.0,0.0,0.000000,0.0,0.0,0.0,2022-01-18 12:26:36,2022-01-18 12:26:43
3,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1HHo8XQfgJRMqaxYJ,5741,2022-01-17,38.0,0.0,0.0,0.000000,0.0,0.0,0.0,2022-01-18 12:26:36,2022-01-18 12:26:43
4,USD,Toolzilla - DE - AMZN,401,EUR,Active,Amazon,1XyrGJbfK6HXSmWyO,5742,2022-01-17,76.0,1.0,0.0,0.022816,0.0,0.0,0.0,2022-01-18 12:26:36,2022-01-18 12:26:43

In [24]:
from datetime import datetime

test = datetime.now().strftime("%H:%M:%S")

print(test)
print(type(test))

12:19:11
<class 'str'>